### ISSUE TITLE
SUNEA io - Awning

### ISSUE THREAD

**Issue by xeor** [nikkow/node-red-contrib-tahoma#1]
Glad to see someone creating a tahoma connector!

I can confirm that this works out of the box with "SUNEA io - Awning". It did take a minute to detect it in the dropdown list, but when it was there, I was able to control it.

It does not look like anything is sent to the output, and position 100 is "in", and 0 is completly out..

Other than that, perfect! 👍

**Comment by frankis78** [comment]
Can you give me some hints on how you did it, regards to the messages you added.
When i inject open, it opens, but when i do the same on close, nothing is happening.
<img width="511" alt="screen shot 2018-05-20 at 01 49 45" src="https://user-images.githubusercontent.com/26933092/40274171-78e73fcc-5bd0-11e8-82fd-f44caf8271ae.png">
<img width="644" alt="screen shot 2018-05-20 at 01 50 24" src="https://user-images.githubusercontent.com/26933092/40274172-7b8bc040-5bd0-11e8-9b24-d14ce9978f7c.png">

**Comment by nikkow** [comment]
@xeor thanks for your feedback! I have updated the README file accordingly 👍  .
