### ISSUE TITLE
Installation problem of v2

### ISSUE THREAD

**Issue by Programmierfreund** [nikkow/node-red-contrib-tahoma#20]
When I install the v2 of node-red-contrib-tahoma using the plugin palette I'm receiving the following error message:

node-red-contrib-tahoma
2.0.0
Error: /data/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma.html does not exist
Error: /data/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma-config.html does not exist
Error: /data/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma-read.html does not exist

The nodes will not activate.  I'm using node-red as container from https://hub.docker.com/r/nodered/node-red running in Container Station on a QNAP NAS. All existing flows are running without problems. I'm not using any special account/user because that was not necessary in the past.
![200301 problem contrib-tahoma v2](https://user-images.githubusercontent.com/59145367/75631058-0c02a500-5bf0-11ea-872d-5c3fb455580b.PNG)

**Comment by nikkow** [comment]
Thank you for the report. There was indeed an issue caused by the new structure when pushing it to npm registry. 2.0.1 fixes this.
