### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by palcooky72** [nikkow/node-red-contrib-tahoma#21]
No issue just wanted to say thanks for the update. I can now uninstall home assistant :-) as I only used that for somfy. But really appreciate your time and efforts in updating this.

P.S. On your wiki for setting up apps on somfy dev site, it takes about 15-20 mins for a new app to become active.

**Comment by nikkow** [comment]
Thank you very much for your comment :)

I have updated the documentation. It now mentions the delay for initial app creations.
