### ISSUE TITLE
Node broken

### ISSUE THREAD

**Issue by bakman2** [nikkow/node-red-contrib-tahoma#22]
Cannot enter my credentials, cannot "link", cannot reset tokens. 

![Screenshot 2020-03-06 at 14 33 21](https://user-images.githubusercontent.com/333960/76087956-7e400480-5fb7-11ea-8257-b1f098323545.jpg)

The node is broken for me, when entering my credentials, the node remains red and node-red give exclamation mark, cannot deploy. The callback url is correct. 
What is going on ?

**Comment by bakman2** [comment]
Ok the callback was incorrect, wiki describes:

>Callback URL: enter the URL of your node-red installation (e.g. if installed locally: http://127.0.0.1:1880).

it should be:

http://127.0.0.1:1880/somfy/callback

**Comment by nikkow** [comment]
Thank you, I have updated the documentation accordingly.
