### ISSUE TITLE
Somfy API seems no longer to respond to node red.

### ISSUE THREAD

**Issue by hmwelsch** [nikkow/node-red-contrib-tahoma#23]
Somfy App on their web site responds OK with approval and valid credentials. Tokens are not expired and efresh of API tokens works flawless too. However, no devices can be found in new nodes and the corresponding fields are greyed out. No data can be received by read nodes that were previously working, nor can any new nodes be defined. On existing nodes site and device entries are filled with 8-digit hex values connected by hyphens. Debug output from nodes is like: {"topic":"","payload":null,"_msgid":"c08144c1.1739a8"}.

**Comment by bakman2** [comment]
Same issue here. I wonder if the whole oauth process could be incorporated into the node without the need to use popups and reset of tokens.

**Comment by bakman2** [comment]
It looks like their ssl/tls certificate expired on March 21st. 
https://www.ssllabs.com/ssltest/analyze.html?d=api.somfy.com

**Comment by bakman2** [comment]
Certificate has been renewed, node is functional again.

**Comment by hmwelsch** [comment]
Great, thanks for evaluating!
