### ISSUE TITLE
impossible to check status frequently ?  

### ISSUE THREAD

**Issue by Loganserval** [nikkow/node-red-contrib-tahoma#28]
hello,
first, I would like to thanks you for the job already done.
The palette work fine for me and I succeed to create all I need in nod red except one function.
I would like to check (every minute for the example) the status of the devices (close a 10 %)
I need to do this because I have multiple way to activate every device. And I would like to synchronize the device state between nod red and the others.
I use the read function but I don’t know how to make it update itself.
Thanks in advance for your feedback
BR
![image](https://user-images.githubusercontent.com/63745848/79491000-118c4100-801e-11ea-9b8e-0f90e232f868.png)

**Comment by nikkow** [comment]
Hello,

Thank you for your support! 😄 
NodeRed exposes an **Inject** node that can be configured to send an output at a given time interval. 

![image](https://user-images.githubusercontent.com/2404378/79632396-24f2f580-815f-11ea-877e-c931c6f0e8c9.png)

**Comment by Loganserval** [comment]
Hi nikkow,
thanks for your answer, I badly understand your block description 
![image](https://user-images.githubusercontent.com/63745848/80850896-bc0b8300-8c1e-11ea-9ddc-488ed9b2c4e7.png)
So the block accept as input the inject block . 
I update my nod-red and it's work :-) thanks again for the work.
I still have one unit that is not visible, it's my garage door (IO engine that working with tahoma otherwise)

**Comment by nikkow** [comment]
Hi @Loganserval,

Thanks for your feedback. The descripton may indeed be a bit confusing in this case. It does not accept **any data** as input (meaning you can't compute the device ID on a node, then pass it to the `tahoma-read` node). However, it is triggered on input, so the inject does the job. :)

Regarding the garage door, I do have the same issue. It seems that garage doors cannot be controlled using the Somfy API.
