### ISSUE TITLE
Example Node Red Switch Config

### ISSUE THREAD

**Issue by Ed2010** [nikkow/node-red-contrib-tahoma#3]
Hi,

how can i use a switch to open or close the Tahoma?

Can you give me an Example?

Thanks.

**Comment by nikkow** [comment]
Hi @Ed2010,

Can you provide more details about what you are trying to achieve? Like a use case? I will then be able to help you :)

Thanks!

**Comment by Ed2010** [comment]
Hi @Nikkow,

thank you for your fast response!
my goal is to operate the shutters via a touch screen and a node-red switch. The touch screen (NEXTION) hangs on an ESP8266. MQTT is running on the ESP. In the node red, I would like to control the roller shutter via MQTT or Switch.

<img width="429" alt="bildschirmfoto 2018-03-02 um 17 25 36" src="https://user-images.githubusercontent.com/34440549/36910074-0a3ea628-1e40-11e8-8a52-e63da3d63f2c.png">


> Actions
Currently, only a few commands are understood by this node. The possible values for the action property are:

open: This will open the device (door, blind...)
close: This will close the device

**Comment by nikkow** [comment]
Hi @Ed2010, 

The Tahoma node expects to receive an object from the parent node (the one that is connected to the Tahoma node input). This object must be set in the `msg.payload` variable by the parent node. For example, if you need to close your blinds, the `msg.payload` you must send to the Tahoma node will look like this:

`{
    "action":"close"
}`

My setup looks like this:

![capture d ecran 2018-03-02 a 18 40 31](https://user-images.githubusercontent.com/2404378/36913132-3dc74910-1e49-11e8-8760-475184c6c857.png)

- The "MQTT" node only sends a 0/1 value indicating whether I should close/open the blinds.
- The "What to do?" node checks this value and triggers either the "Close" or "Open" nodes.
- The "Close" and "Open" nodes are of type "change" (you might find it in the "function" category). They are just setting the proper payload based on the action I want to do: 

![capture d ecran 2018-03-02 a 18 44 54](https://user-images.githubusercontent.com/2404378/36913330-ddad5e06-1e49-11e8-9f7b-be76d8da028d.png)

Let's say I want to close the blinds, here is the chain that is going to be triggered:

- MQTT will send a `0` 
- The "What to do?" node will detect that `0` and route it to the "Close" node.
- The close node will set the value of `msg.payload` to `{"action":"close"}` and forward it to the Tahoma node
- The Tahoma node will close the blind.

I hope this helped :)

**Comment by Ed2010** [comment]
Hi @nikkow 

great, it works! Thanks a lot!!!

I needed something to implement your solution until I realized
"Change" must be from type "json".

Now it works with a switch. The mqtt will i´m testing now.
