### ISSUE TITLE
Will window/door sensors be added

### ISSUE THREAD

**Issue by frankis78** [nikkow/node-red-contrib-tahoma#30]
On old installation i could get statur of the window sensors.
But i dont get these devices in the dropdown list.
I can only see the 3 screens and tahoma
Am i doing anything wrong?

**Comment by nikkow** [comment]
Hi @frankis78,
The list of devices exposed through this API is quite limited. Shutters and Blinds seem to be the only devices that are fully implemented (based on the [API documentation](https://developer.somfy.com/products-services-informations)). It is of course not excluded that Somfy will add more devices.
