### ISSUE TITLE
Add support for orientation/rotation of blinds

### ISSUE THREAD

**Issue by marekhalmo** [nikkow/node-red-contrib-tahoma#32]
Hello,

Yesterday i got new blinds on my house, i tried to integrate them with node red which took a while.
Currently it is only possible to set customPossition on the blinds.
I would like to controll the rotation/orientation as well (for the homecontrol io motors only).

I was looking in to the code and i did the change necessary. I would like to merge the changes to develop for everyone to use (the change is quite simple to do)..

the change is in tahoma.ts to add a new option (line 96)
                case 'customRotation':
                    commandName = 'rotation';
                    parameters = [{ name: 'orientation', value: parseInt(msg.payload.orientation, 10) }];
                    statusProgressText = 'Rotating to ' + msg.payload.orientation + 'degrees...';
                    statusDoneText = 'Rotated to ' + msg.payload.orientation + '%'; 
                    break;

How can i contribute? Is it possible to commit to develop or can you create a branch that i can use?

Thank you!

**Comment by nikkow** [comment]
Hi @marekhalmo, 

If you would like to submit a new feature or a fix, do not hesitate to fork the repository and submit a pull-request for your changes :) I'll happily integrate them to the codebase. 

By the way, your comment made me realize that there one important thing missing on the repo: a contributor guide. I will add that! Thanks for point that out!

**Comment by marekhalmo** [comment]
I did the change request.. feel free to review the changes

**Comment by nikkow** [comment]
Thank you for the contribution :) The pull-request was merged. The fix will be part of the next release.
