### ISSUE TITLE
[COLABORATION] The session expired issue

### ISSUE THREAD

**Issue by marekhalmo** [nikkow/node-red-contrib-tahoma#49]
Hello,

I'm here to solve the messy session expired issue once for all.
The goal:
- is to implement automatic fix for session expired by having additional fields for login/pwd in the configuration node
- try to figure out why this happens and why some days the original app is working but this plugin does not
- Inspiration comes from https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.somfytahoma

Motivation:
- I get this issue at least 1/week, my wife/kids don't know what to do to restore the system.
- It is very annoying to have to open some page to fix this
- OpenHab plugin is having this functionality - why should this be a problem

@nikkow i know you are busy - but please assist - at least you could push a new version/release when this is done

**Comment by panjazzon** [comment]
Hi marekhalmo, did you make any progres on your project?

**Comment by marekhalmo** [comment]
Hello @panjazzon, not much progress so far.. I'm kinda busy now..

**Comment by marekhalmo** [comment]
Hello,

i have a working login in soapui now.. have to rewrite it to JS to make it work first

**Comment by marekhalmo** [comment]
I have trouble deploying the package to my local node-red windows .. any help?

If i try to integrate with https://nodered.org/docs/creating-nodes/first-node#testing-your-node-in-node-red i will get an error loading some list..

same with npm run build

**Comment by marekhalmo** [comment]
I have a working soapui example where i get to the point the api is redirecting me to a page with valid token to fetch access and refresh tokens (the stuff you need to click manually when your tokens get expired.

Going to try to reimplement this to javascript now..

**Comment by nikkow** [comment]
Hello,

Sorry for the long time with no response. Somfy recently announced a new API (yeah... another one) that would allow this node to discuss directly with the Tahoma box without having to deal with any server-side API (apart from the setup). The first tests are very promising and I am pretty confident that this new announcement is the long-expected solution. 

Best,
N.

**Comment by nandibrenna** [comment]
Hello,
is there any progress with the new API?
Anything to test?

**Comment by nikkow** [comment]
The beta version of 3.0.0 was released a few minutes ago. If you feel like testing it, please install it from the beta channel (from the node-red folder, from your terminal):

```
npm i node-red-contrib-tahoma@beta
```

Please note that this is a **beta** version. You might encounter issues while using it (as it is not considered as being ready for production).

Best,
N.

**Comment by marekhalmo** [comment]
Yes.. yes yes!.. i will check this out! Thank you! This is probably the last issue that is bugging me with my smart house ...

**Comment by marekhalmo** [comment]
Hello.. i checked last develop yesterday.. after fixing the custom rotation issue (https://github.com/nikkow/node-red-contrib-tahoma/issues/61) everything seems to be working fine.. 

Because this works on the local api i think it is not necessary to fix this issue here. 
Thank you!
CLOSED
